config/routes.rb
HappyRep::Application.routes.draw do
  resources :tasks

  resources :animals

  resources :employees

  resources :loans

  resources :restitutions

  resources :events

  resources :books

  resources :bills

  resources :admins

  resources :residents

  resources :formers

  resources :aggregates

  resources :vacines

  devise_for :users, :path => '/'

  root :to => "root#index"

  get 'event_report' => 'report#events'

  get 'expense_report' => 'report#expenses'

  get 'restitution_report' => 'report#restitutions'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    user_accessor = UserAccessor.new(user)
    profile_accessor = user_accessor.profile

    if profile_accessor.admin?
      can :manage, :admin
      can :manage, :aggregate
      can :manage, :animal
      can :manage, :bill
      can :manage, :book
      can :manage, :employee
      can :manage, :event
      can :manage, :former
      can :manage, :loan
      can :manage, :report
      can :manage, :resident
      can :manage, :restitution
      can :manage, :task
      can :manage, :vacine
    elsif profile_accessor.resident?
      can [ :index, :show ], :admin
      can [ :index, :show, :new, :create ], :aggregate
      can :manage, :animal
      can :manage, :bill
      can :manage, :book
      can [ :index, :show ], :employee
      can [ :index, :show, :new, :create ], :event
      can [ :index, :show, :new, :create ], :former
      can :manage, :loan
      can :manage, :report
      can [ :index, :show, :new, :create ], :resident
      can [ :index, :show, :new, :create ], :restitution
      can :manage, :task
      can [ :index, :show, :new, :create ], :vacine
    elsif profile_accessor.former?
      can [ :index, :show ], :admin
      can [ :index, :show ], :aggregate
      can :manage, :loan
      can [ :index, :show ], :former
      can [ :index, :show ], :resident
    elsif profile_accessor.aggregate?
      can [ :index, :show ], :admin
      can [ :index, :show ], :aggregate
      can [ :index, :show ], :event
      can [ :index, :show ], :former
      can [ :index, :show ], :resident
    end
  end
end

app/controllers/admins_controller.rb
class AdminsController < AuthorizedController
  def index
    @admins = advanced_search(params[:name])
  end
end

app/controllers/aggregates_controller.rb
class AggregatesController < AuthorizedController
  def index
    @aggregates = advanced_search(params[:name])
  end
end

app/controllers/animals_controller.rb
class AnimalsController < AuthorizedController
  def index
    @animals = advanced_search(params[:name], params[:race])
  end
end

app/controllers/application_controller.rb
class ApplicationController < Zertico::Controller
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery
end

app/controllers/authorized_controller.rb
class AuthorizedController < ApplicationController
  before_filter :authenticate_user!
  authorize_resource :class => false

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
end

app/controllers/bills_controller.rb
class BillsController < AuthorizedController
  def index
    @bills = advanced_search(params[:expiration_date], params[:payment_date])
  end
end

app/controllers/books_controller.rb
class BooksController < AuthorizedController
  def index
    @books = advanced_search(params[:name], params[:author])
  end
end

app/controllers/employees_controller.rb
class EmployeesController < AuthorizedController
  def index
    @employees = advanced_search(params[:name], params[:date])
  end
end

app/controllers/events_controller.rb
class EventsController < AuthorizedController
  def index
    @events = advanced_search(params[:name], params[:date])
  end
end

app/controllers/formers_controller.rb
class FormersController < AuthorizedController
  def index
    @formers = advanced_search(params[:name])
  end
end

app/controllers/loans_controller.rb
class LoansController < AuthorizedController
  def index
    @loans = advanced_search(params[:dweller], params[:date])
  end
end

app/controllers/report_controller.rb
class ReportController < AuthorizedController
  def events
    @events, @profit = report_events
  end

  def expenses
    @bills, @total = report_expenses
  end

  def restitutions
    @restitutions, @total = report_restitutions
  end
end

app/controllers/residents_controller.rb
class ResidentsController < AuthorizedController
  def index
    @residents = advanced_search(params[:name])
  end
end

app/controllers/restitutions_controller.rb
class RestitutionsController < AuthorizedController
  def index
    @restitutions = advanced_search(params[:item], params[:date])
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
    @users = birthdays
  end
end

app/controllers/tasks_controller.rb
class TasksController < AuthorizedController
  def index
    @tasks = advanced_search(params[:name], params[:date])
  end
end

app/controllers/vacines_controller.rb
class VacinesController < AuthorizedController
end

app/views/admin/users/index.html.erb
<table>
  <thead>
  <tr>
    <th>Email</th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to "Detalhar", ['admin', user] %></td>
        <td><%= link_to "Apagar", ['admin', user], :data => { :confirm => "Você tem certeza?" }, :method => :delete %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/admins/_form.html.erb
<% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> não permitiram esse admin ser criado:</h2>

      <ul>
        <% @admin.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<% unless @admin.persisted? %>
    <div class="field">
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </div>
<% end %>
<%= f.fields_for(:profile) do |p| %>
    <div class="field">
      <%= p.label :name %><br />
      <%= p.text_field :name %>
    </div>
    <div class="field">
      <%= p.label :birthday %><br />
      <%= p.date_select :birthday %>
    </div>
    <div class="field">
      <%= p.label :cpf %><br />
      <%= p.text_field :cpf %>
    </div>
    <div class="field">
      <%= p.label :college %><br />
      <%= p.text_field :college %>
    </div>
    <div class="field">
      <%= p.label :course %><br />
      <%= p.text_field :course %>
    </div>
    <div class="field">
      <%= p.label :admission %><br />
      <%= p.date_select :admission %>
    </div>
    <div class="field">
      <%= p.label :hometown %><br />
      <%= p.text_field :hometown %>
    </div>
    <div class="field">
      <%= p.label :bio %><br />
      <%= p.text_area :bio %>
    </div>
    <div class="field">
      <%= p.label :phone %><br />
      <%= p.text_field :phone %>
    </div>
    <div class="field">
      <%= p.label :address %><br />
      <%= p.text_field :address %>
    </div>
<% end %>
<div class="actions">
  <%= f.submit 'Criar Admin' %>
</div>

app/views/admins/edit.html.erb
<%= form_for(@admin, :url => admin_path(@admin)) do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>
<% end %>

<%= link_to 'Visualizar', admin_path(@admin) %> |
<%= link_to 'Voltar', admins_path %>

app/views/admins/index.html.erb
<%= form_tag(admins_path, :method => "get") do %>
    <div class="container-fluid">
      <div class="row-fluid" >
        <div class="span3">
          Nome:
        </div>
        <div class="span3 row-form">
          <input type="text" id="name" name="name" />
        </div>
      </div>
    </div>
    <%= button_tag("Consultar") %>

<% end %>


<table class="table table-striped">
  <tr>
    <th>Nome</th>
    <th>Aniversário</th>
    <th>CPF</th>
    <th>Telefone</th>
    <th></th>
    <th></th>
  </tr>

  <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.profile.name %></td>
        <td><%= l admin.profile.birthday %></td>
        <td><%= admin.profile.cpf %></td>
        <td><%= admin.profile.phone %></td>
        <td><%= link_to "Detalhar", admin_path(admin) %></td>
        <td><%= link_to "Apagar", admin_path(admin), :data => { :confirm => "Você tem certeza?" }, :method => :delete %></td>
      </tr>
  <% end %>
</table>

<br />

<%= link_to 'Novo Admin', new_admin_path %>

app/views/admins/new.html.erb
<%= form_for(@admin, :url => admins_path) do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>
<% end %>

<%= link_to 'Voltar', admins_path %>

app/views/admins/show.html.erb
<p>
  <b>Nome:</b>
  <%= @admin.profile.name %>
</p>
<p>
  <b>Aniversário:</b>
  <%= l @admin.profile.birthday %>
</p>
<p>
  <b>CPF:</b>
  <%= @admin.profile.cpf %>
</p>
<p>
  <b>Faculdade:</b>
  <%= @admin.profile.college %>
</p>
<p>
  <b>Curso:</b>
  <%= @admin.profile.course %>
</p>
<p>
  <b>Ano de Ingresso:</b>
  <%= l @admin.profile.admission if @admin.profile.admission %>
</p>
<p>
  <b>Cidade Natal:</b>
  <%= @admin.profile.hometown %>
</p>
<p>
  <b>Descrição:</b>
  <%= @admin.profile.bio %>
</p>
<p>
  <b>Telefone:</b>
  <%= @admin.profile.phone %>
</p>
<p>
  <b>Endereço:</b>
  <%= @admin.profile.address %>
</p>

<%= link_to 'Editar', edit_admin_path(@admin) %> |
<%= link_to 'Voltar', admins_path %>

app/views/aggregates/edit.html.erb
<%= form_for(@aggregate, :url => aggregate_path(@aggregate)) do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>
<% end %>

<%= link_to 'Visualizar', aggregate_path(@aggregate) %> |
<%= link_to 'Voltar', aggregates_path %>

app/views/aggregates/index.html.erb
<%= form_tag(formers_path, :method => "get") do %>
    <div class="container-fluid">
      <div class="row-fluid" >
        <div class="span3">
          Nome:
        </div>
        <div class="span3 row-form">
          <input type="text" id="name" name="name" />
        </div>
      </div>
    </div>
    <%= button_tag("Consultar") %>

<% end %>


<table class="table table-striped">
  <tr>
    <th>Nome</th>
    <th>Aniversário</th>
    <th>CPF</th>
    <th>Telefone</th>
    <th></th>
    <th></th>
  </tr>


  <% @aggregates.each do |aggregate| %>
      <tr>
        <td><%= aggregate.profile.name %></td>
        <td><%= l aggregate.profile.birthday %></td>
        <td><%= aggregate.profile.cpf %></td>
        <td><%= aggregate.profile.phone %></td>
        <td><%= link_to "Detalhar", aggregate_path(aggregate) %></td>
        <td><%= link_to "Apagar", aggregate_path(aggregate), :data => { :confirm => "Você tem certeza?" }, :method => :delete %></td>
      </tr>
  <% end %>
</table>

<br />

<%= link_to 'Novo Agregado', new_aggregate_path %>

app/views/aggregates/new.html.erb
<%= form_for(@aggregate, :url => aggregates_path) do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>
<% end %>

<%= link_to 'Voltar', aggregates_path %>

app/views/aggregates/show.html.erb
<p>
  <b>Nome:</b>
  <%= @aggregate.profile.name %>
</p>
<p>
  <b>Aniversário:</b>
  <%= l @aggregate.profile.birthday %>
</p>
<p>
  <b>CPF:</b>
  <%= @aggregate.profile.cpf %>
</p>
<p>
  <b>Faculdade:</b>
  <%= @aggregate.profile.college %>
</p>
<p>
  <b>Curso:</b>
  <%= @aggregate.profile.course %>
</p>
<p>
  <b>Ano de Ingresso:</b>
  <%= l @aggregate.profile.admission if @aggregate.profile.admission %>
</p>
<p>
  <b>Cidade Natal:</b>
  <%= @aggregate.profile.hometown %>
</p>
<p>
  <b>Descrição:</b>
  <%= @aggregate.profile.bio %>
</p>
<p>
  <b>Telefone:</b>
  <%= @aggregate.profile.phone %>
</p>
<p>
  <b>Endereço:</b>
  <%= @aggregate.profile.address %>
</p>

<%= link_to 'Editar', edit_aggregate_path(@aggregate) %> |
<%= link_to 'Voltar', aggregates_path %>

app/views/animals/edit.html.erb
<%= render 'form' %>

<%= link_to 'Visualizar', @animal %> |
<%= link_to 'Voltar', animals_path %>

app/views/animals/index.html.erb
<%= form_tag(animals_path, :method => "get") do %>
    <div class="container-fluid">
      <div class="row-fluid" >
        <div class="span3">
          Nome:
        </div>
        <div class="span3 row-form">
          <input type="text" id="name" name="name" />
        </div>
      </div>
      <div class="row-fluid" >
        <div class="span3">
          Raça:
        </div>
        <div class="span3 row-form">
          <input type="text" id="race" name="race" />
        </div>
      </div>
    </div>
    <%= button_tag("Consultar") %>

<% end %>


<table class="table table-striped">
  <tr>
    <th>Nome</th>
    <th>Espécie</th>
    <th>Raça</th>
    <th>Data de Nascimento</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @animals.each do |animal| %>
  <tr>
    <td><%= animal.name %></td>
    <td><%= animal.species %></td>
    <td><%= animal.race %></td>
    <td><%= l animal.birth_date %></td>
    <td><%= link_to 'Visualizar', animal %></td>
    <td><%= link_to 'Editar', edit_animal_path(animal) %></td>
    <td><%= link_to 'Apagar', animal, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Novo animal', new_animal_path %>

app/views/animals/new.html.erb
<%= render 'form' %>

<%= link_to 'Voltar', animals_path %>

app/views/animals/show.html.erb
<p>
  <b>Nome:</b>
  <%= @animal.name %>
</p>

<p>
  <b>Espécie:</b>
  <%= @animal.species %>
</p>

<p>
  <b>Raça:</b>
  <%= @animal.race %>
</p>

<p>
  <b>Data de Nascimento:</b>
  <%= l @animal.birth_date %>
</p>


<%= link_to 'Editar', edit_animal_path(@animal) %> |
<%= link_to 'Voltar', animals_path %>

app/views/bills/edit.html.erb
<%= render 'form' %>

<%= link_to 'Visualizar', @bill %> |
<%= link_to 'Voltar', bills_path %>

app/views/bills/index.html.erb
<%= form_tag(bills_path, :method => "get") do %>
  <div class="container-fluid">
    <div class="row-fluid" >
      <div class="span3">
        Data de Vencimento:
      </div>
      <div class="span3 row-form">
        <input type="text" id="expiration_date" name="expiration_date" placeholder="Exemplo: 01/01/1992" />
      </div>
    </div>
    <div class="row-fluid" >
      <div class="span3">
        Data de Pagamento:
      </div>
      <div class="span3 row-form">
        <input type="text" id="payment_date" name="payment_date" placeholder="Exemplo: 01/01/1992" />
      </div>
    </div>
  </div>
  <%= button_tag("Consultar") %>

<% end %>


<table class="table table-striped">
  <thead>
  <tr>
    <th>Descrição</th>
    <th>Tipo</th>
    <th>Valor</th>
    <th>Data de Vencimento</th>
    <th>Data de Pagamento</th>
    <th>Multa</th>
    <th>Juros</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.description %></td>
        <td><%= bill.kind %></td>
        <td><%= bill.value %></td>
        <td><%= l bill.expiration_date %></td>
        <td><%= l bill.payment_date if bill.payment_date %></td>
        <td><%= bill.penalty %></td>
        <td><%= bill.interest %></td>
        <td><%= link_to 'Visualizar', bill %></td>
        <td><%= link_to 'Editar', edit_bill_path(bill) %></td>
        <td><%= link_to 'Apagar', bill, method: :delete, data: { confirm: 'Tem certeza disso?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'Nova conta', new_bill_path %>

app/views/bills/new.html.erb
<%= render 'form' %>

<%= link_to 'Voltar', bills_path %>

app/views/bills/show.html.erb
<p>
  <b>Descrição:</b>
  <%= @bill.description %>
</p>

<p>
  <b>Tipo:</b>
  <%= @bill.kind %>
</p>

<p>
  <b>Valor:</b>
  <%= @bill.value %>
</p>

<p>
  <b>Data de Vencimento:</b>
  <%= l @bill.expiration_date %>
</p>

<p>
  <b>Data de Pagamento:</b>
  <%= l @bill.payment_date if @bill.payment_date %>
</p>

<p>
  <b>Multa:</b>
  <%= @bill.penalty %>
</p>

<p>
  <b>Juros:</b>
  <%= @bill.interest %>
</p>


<%= link_to 'Editar', edit_bill_path(@bill) %> |
<%= link_to 'Voltar', bills_path %>

app/views/employees/edit.html.erb
<%= render 'form' %>

<%= link_to 'Visualizar', @employee %> |
<%= link_to 'Voltar', employees_path %>

app/views/employees/index.html.erb
<%= form_tag(employees_path, :method => "get") do %>
    <div class="container-fluid">
      <div class="row-fluid" >
        <div class="span3">
          Nome:
        </div>
        <div class="span3 row-form">
          <input type="text" id="name" name="name" />
        </div>
      </div>
      <div class="row-fluid" >
        <div class="span3">
          Data de Admissão:
        </div>
        <div class="span3 row-form">
          <input type="text" id="date" name="date" />
        </div>
      </div>
    </div>
    <%= button_tag("Consultar") %>

<% end %>


<table class="table table-striped">
  <tr>
    <th>Nome</th>
    <th>Endereço</th>
    <th>Carteira de Trabalho</th>
    <th>CPF</th>
    <th>Data de Admissão</th>
    <th>Salário</th>
    <th>Telefone</th>
    <th>Data de Demissão</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @employees.each do |employee| %>
  <tr>
    <td><%= employee.name %></td>
    <td><%= employee.address %></td>
    <td><%= employee.work_card %></td>
    <td><%= employee.register %></td>
    <td><%= l employee.admission_date %></td>
    <td><%= employee.salary %></td>
    <td><%= employee.phone %></td>
    <td><%= l employee.demission_date if employee.demission_date %></td>
    <td><%= link_to 'Visualizar', employee %></td>
    <td><%= link_to 'Editar', edit_employee_path(employee) %></td>
    <td><%= link_to 'Apagar', employee, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Novo empregado', new_employee_path %>

app/views/employees/new.html.erb
<%= render 'form' %>

<%= link_to 'Voltar', employees_path %>

app/views/employees/show.html.erb
<p>
  <b>Nome:</b>
  <%= @employee.name %>
</p>

<p>
  <b>Endereço:</b>
  <%= @employee.address %>
</p>

<p>
  <b>Carteira de Trabalho:</b>
  <%= @employee.work_card %>
</p>

<p>
  <b>CPF:</b>
  <%= @employee.register %>
</p>

<p>
  <b>Data de Admissão:</b>
  <%= l @employee.admission_date %>
</p>

<p>
  <b>Salário:</b>
  <%= @employee.salary %>
</p>

<p>
  <b>Telefone:</b>
  <%= @employee.phone %>
</p>

<p>
  <b>Data de Demissão:</b>
  <%= l @employee.demission_date if @employee.demission_date %>
</p>


<%= link_to 'Editar', edit_employee_path(@employee) %> |
<%= link_to 'Voltar', employees_path %>

app/views/formers/edit.html.erb
<%= form_for(@former, :url => former_path(@former)) do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>
<% end %>

<%= link_to 'Visualizar', former_path(@former) %> |
<%= link_to 'Voltar', formers_path %>

app/views/formers/index.html.erb
<%= form_tag(formers_path, :method => "get") do %>
    <div class="container-fluid">
      <div class="row-fluid" >
        <div class="span3">
          Nome:
        </div>
        <div class="span3 row-form">
          <input type="text" id="name" name="name" />
        </div>
      </div>
    </div>
    <%= button_tag("Consultar") %>

<% end %>


<table class="table table-striped">
  <tr>
    <th>Nome</th>
    <th>Aniversário</th>
    <th>CPF</th>
    <th>Telefone</th>
    <th></th>
    <th></th>
  </tr>

  <% @formers.each do |former| %>
      <tr>
        <td><%= former.profile.name %></td>
        <td><%= l former.profile.birthday %></td>
        <td><%= former.profile.cpf %></td>
        <td><%= former.profile.phone %></td>
        <td><%= link_to "Detalhar", former_path(former) %></td>
        <td><%= link_to "Apagar", former_path(former), :data => { :confirm => "Você tem certeza?" }, :method => :delete %></td>
      </tr>
  <% end %>
</table>

<br />

<%= link_to 'Novo Ex-Morador', new_former_path %>

app/views/formers/new.html.erb
<%= form_for(@former, :url => formers_path) do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>
<% end %>

<%= link_to 'Voltar', formers_path %>

app/views/formers/show.html.erb
<p>
  <b>Nome:</b>
  <%= @former.profile.name %>
</p>
<p>
  <b>Aniversário:</b>
  <%= l @former.profile.birthday %>
</p>
<p>
  <b>CPF:</b>
  <%= @former.profile.cpf %>
</p>
<p>
  <b>Faculdade:</b>
  <%= @former.profile.college %>
</p>
<p>
  <b>Curso:</b>
  <%= @former.profile.course %>
</p>
<p>
  <b>Ano de Ingresso:</b>
  <%= l @former.profile.admission if @former.profile.admission %>
</p>
<p>
  <b>Cidade Natal:</b>
  <%= @former.profile.hometown %>
</p>
<p>
  <b>Descrição:</b>
  <%= @former.profile.bio %>
</p>
<p>
  <b>Telefone:</b>
  <%= @former.profile.phone %>
</p>
<p>
  <b>Endereço:</b>
  <%= @former.profile.address %>
</p>

<%= link_to 'Editar', edit_former_path(@former) %> |
<%= link_to 'Voltar', formers_path %>

app/views/residents/edit.html.erb
<%= form_for(@resident, :url => resident_path(@resident)) do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>
<% end %>

<%= link_to 'Visualizar', resident_path(@resident) %> |
<%= link_to 'Voltar', residents_path %>

app/views/residents/index.html.erb
<%= form_tag(residents_path, :method => "get") do %>
    <div class="container-fluid">
      <div class="row-fluid" >
        <div class="span3">
          Nome:
        </div>
        <div class="span3 row-form">
          <input type="text" id="name" name="name" />
        </div>
      </div>
    </div>
    <%= button_tag("Consultar") %>

<% end %>


<table class="table table-striped">
  <tr>
    <th>Nome</th>
    <th>Aniversário</th>
    <th>CPF</th>
    <th>Telefone</th>
    <th></th>
    <th></th>
  </tr>


  <% @residents.each do |resident| %>
      <tr>
        <td><%= resident.profile.name %></td>
        <td><%= l resident.profile.birthday %></td>
        <td><%= resident.profile.cpf %></td>
        <td><%= resident.profile.phone %></td>
        <td><%= link_to "Detalhar", resident_path(resident) %></td>
        <td><%= link_to "Apagar", resident_path(resident), :data => { :confirm => "Você tem certeza?" }, :method => :delete %></td>
      </tr>
  <% end %>
</table>

<br />

<%= link_to 'Novo Morador', new_resident_path %>

app/views/residents/new.html.erb
<%= form_for(@resident, :url => residents_path) do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>
<% end %>

<%= link_to 'Voltar', residents_path %>

app/views/residents/show.html.erb
<p>
  <b>Nome:</b>
  <%= @resident.profile.name %>
</p>
<p>
  <b>Aniversário:</b>
  <%= l @resident.profile.birthday %>
</p>
<p>
  <b>CPF:</b>
  <%= @resident.profile.cpf %>
</p>
<p>
  <b>Faculdade:</b>
  <%= @resident.profile.college %>
</p>
<p>
  <b>Curso:</b>
  <%= @resident.profile.course %>
</p>
<p>
  <b>Ano de Ingresso:</b>
  <%= l @resident.profile.admission if @resident.profile.admission %>
</p>
<p>
  <b>Cidade Natal:</b>
  <%= @resident.profile.hometown %>
</p>
<p>
  <b>Descrição:</b>
  <%= @resident.profile.bio %>
</p>
<p>
  <b>Telefone:</b>
  <%= @resident.profile.phone %>
</p>
<p>
  <b>Endereço:</b>
  <%= @resident.profile.address %>
</p>

<%= link_to 'Editar', edit_resident_path(@resident) %> |
<%= link_to 'Voltar', residents_path %>

app/views/root/index.html.erb
<% if @users.empty? %>
 Não existem aniversariantes hoje.
<% else %>
  Os aniversariantes são:
  <% @users.each do |user| %>
    <%= user.name %>
    <br>
  <% end %>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form' %>

<%= link_to 'Visualizar', @task %> |
<%= link_to 'Voltar', tasks_path %>

app/views/tasks/index.html.erb
<%= form_tag(tasks_path, :method => "get") do %>
    <div class="container-fluid">
      <div class="row-fluid" >
        <div class="span3">
          Nome:
        </div>
        <div class="span3 row-form">
          <input type="text" id="name" name="name" />
        </div>
      </div>
      <div class="row-fluid" >
        <div class="span3">
          Data:
        </div>
        <div class="span3 row-form">
          <input type="text" id="date" name="date" placeholder="Exemplo: 01/01/1992" />
        </div>
      </div>
    </div>
    <%= button_tag("Consultar") %>

<% end %>


<table class="table table-striped">
  <tr>
    <th>Nome</th>
    <th>Descrição</th>
    <th>Data de Início</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.name %></td>
    <td><%= task.description %></td>
    <td><%= l task.start_date if task.start_date %></td>
    <td><%= link_to 'Visualizar', task %></td>
    <td><%= link_to 'Editar', edit_task_path(task) %></td>
    <td><%= link_to 'Apagar', task, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nova tarefa', new_task_path %>

app/views/tasks/new.html.erb
<%= render 'form' %>

<%= link_to 'Voltar', tasks_path %>

app/views/tasks/show.html.erb
<p>
  <b>Nome:</b>
  <%= @task.name %>
</p>

<p>
  <b>Descrição:</b>
  <%= @task.description %>
</p>

<p>
  <b>Data de Início:</b>
  <%= l @task.start_date if @task.start_date %>
</p>


<%= link_to 'Editar', edit_task_path(@task) %> |
<%= link_to 'Voltar', tasks_path %>